# Generated by Django 3.2 on 2021-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_ordermodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_date',
            field=models.DateField(blank=True, max_length=128, null=True),
        ),
    ]
